[package]
name = "polygon"
version = "0.1.0"
authors = ["Sebastian Rollen <rollenseb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3", optional = true }
reqwest = { version = "0.10", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"
tokio-tungstenite = { version = "0.13", features = ["stream", "tls"], optional = true }
tokio = { version = "1.0", default-features = false, features = ["net"], optional = true}

[dev-dependencies]
tokio = { version = "1.0", default-features = false, features = ["macros"] }

[features]
default = ["rest", "ws"]
rest = ["reqwest"]
ws = ["tokio-tungstenite", "tokio/net", "futures"]
